FROM python:3.12.3-slim
RUN pip install --upgrade pip
# Copy the requirements file into the container at /app
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN apt-get update && apt-get install -y libhdf5-dev
# Install h5py with no-binary flag
RUN pip install --no-binary h5py h5py
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5400
CMD ["python", "chatbot.py"]
